// Code generated by go run ./tools/brandtokens. DO NOT EDIT.

package main

const (
	primaryDefault = "rgb(61, 143, 209)"
	primaryLight   = "rgb(90, 159, 216)"

	secondaryDefault = "rgb(240, 176, 122)"
	accentDefault    = "rgb(168, 158, 105)"

	neutral100 = "rgb(230, 230, 230)"
	neutral400 = "rgb(153, 153, 153)"
	neutral600 = "rgb(102, 102, 102)"
	neutral700 = "rgb(77, 77, 77)"
	neutral800 = "rgb(51, 51, 51)"
	neutral900 = "rgb(26, 26, 26)"
)
