//go:generate go run . -input ../../node_modules/@amansanoj/brand/tokens.json -output ../../brand_tokens_gen.go

package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type tokenFile struct {
	Color struct {
		RGB struct {
			Dark struct {
				Base struct {
					Text       string `json:"text"`
					Background string `json:"background"`
					Primary    string `json:"primary"`
					Secondary  string `json:"secondary"`
					Accent     string `json:"accent"`
				} `json:"base"`
				Text struct {
					Value100 string `json:"100"`
					Value400 string `json:"400"`
					Value600 string `json:"600"`
					Value700 string `json:"700"`
					Value800 string `json:"800"`
				} `json:"text"`
				Background struct {
					Value700 string `json:"700"`
					Value800 string `json:"800"`
					Value900 string `json:"900"`
				} `json:"background"`
				Primary struct {
					Value400 string `json:"400"`
				} `json:"primary"`
			} `json:"dark"`
		} `json:"rgb"`
	} `json:"color"`
}

func main() {
	inputPath := flag.String("input", "", "path to tokens.json")
	outputPath := flag.String("output", "", "path to write the generated Go file")
	flag.Parse()

	if strings.TrimSpace(*inputPath) == "" || strings.TrimSpace(*outputPath) == "" {
		fmt.Fprintln(os.Stderr, "usage: go run ./tools/brandtokens -input /path/to/tokens.json -output brand_tokens_gen.go")
		os.Exit(2)
	}

	data, err := os.ReadFile(*inputPath)
	if err != nil {
		fatal(err)
	}

	var tokens tokenFile
	if err := json.Unmarshal(data, &tokens); err != nil {
		fatal(err)
	}

	content := fmt.Sprintf(`// Code generated by go run ./tools/brandtokens. DO NOT EDIT.

package main

const (
	primaryDefault = %q
	primaryLight   = %q

	secondaryDefault = %q
	accentDefault    = %q

	neutral100 = %q
	neutral400 = %q
	neutral600 = %q
	neutral700 = %q
	neutral800 = %q
	neutral900 = %q
)
`,
		tokens.Color.RGB.Dark.Base.Primary,
		tokens.Color.RGB.Dark.Primary.Value400,
		tokens.Color.RGB.Dark.Base.Secondary,
		tokens.Color.RGB.Dark.Base.Accent,
		tokens.Color.RGB.Dark.Text.Value100,
		tokens.Color.RGB.Dark.Text.Value400,
		tokens.Color.RGB.Dark.Text.Value600,
		tokens.Color.RGB.Dark.Text.Value700,
		tokens.Color.RGB.Dark.Text.Value800,
		tokens.Color.RGB.Dark.Background.Value900,
	)

	if err := os.MkdirAll(filepath.Dir(*outputPath), 0o755); err != nil {
		fatal(err)
	}
	if err := os.WriteFile(*outputPath, []byte(content), 0o644); err != nil {
		fatal(err)
	}
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
